try {
    node('BGC-BE-TEST63CD') {
        deleteDir()
        dir('project'){
            git credentialsId: '56e6dec6-558f-40a8-8d81-23bff8ebb509', url: 'git@el2604.bc:FOT-Official/fot.git'
            withEnv(["PATH+NODE=/msservice/app/node/bin","HTTPS_PROXY=http://el2604:8080","HTTP_PROXY=http://el2604:8080"]) {

                stage 'build & package'
                    sh 'node -v'
                    sh 'npm install'
                    sh 'npm run package'
                    dir("packages"){
                        sh 'zip -r electron-poc.zip electron-iframe-resize-example-win32-x64/'
                        archive 'ep_package.zip'
                    }
            }
        }
    }

    currentBuild.result = "SUCCESS"
    mail body: "Build was a success! Check details at ${env.BUILD_URL}console.", from: "architecture.jenkins@belgacom.be", subject: "Build SUCCESS in Jenkins: ${env.JOB_NAME} # ${env.BUILD_NUMBER}", to: "pxs.simone.fot@proximus.com"

} catch (e){
    currentBuild.result = "FAILED"
    // mail body: "Please go to ${env.BUILD_URL}console.", from: "architecture.jenkins@belgacom.be", subject: "Build failed in Jenkins: ${env.JOB_NAME} # ${env.BUILD_NUMBER}", to: "pxs.simone.fot@proximus.com"
    throw e
}
